# create-user:
#    path: /user #url за яким йде виклик методу у роутера
#    controller: Portmone\Controller\CreateUserController::createAction #шлях до контролеру і виклик методу для створення юзера
#
# get-auth:
#    path: /auth #url за яким йде виклик методу у роутера
#    controller: Portmone\Controller\UserAuthController::userAuth #шлях до контролеру і виклик методу для створення юзера
